name: Build and Release Cyclone

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Build?'
        type: boolean
        required: false
        default: true
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ cmake libomp-dev libboost-all-dev

    - name: Clone Cyclone repository
      run: git clone https://github.com/Dookoo2/Cyclone.git

    - name: Build AVX2 version
      run: |
        cd Cyclone/Cyclone_avx2
        g++ -std=c++17 -Ofast -funroll-loops -ftree-vectorize -fstrict-aliasing \
            -fno-semantic-interposition -fvect-cost-model=unlimited \
            -fno-trapping-math -fipa-ra -fipa-modref -flto -fassociative-math \
            -fopenmp -mavx2 -mbmi2 -madx \
            -o Cyclone_avx2 \
            Cyclone.cpp SECP256K1.cpp Int.cpp IntGroup.cpp IntMod.cpp Point.cpp \
            ripemd160_avx2.cpp p2pkh_decoder.cpp sha256_avx2.cpp

    - name: Build AVX512 version
      run: |
        cd Cyclone/Cyclone_avx512
        g++ -std=c++17 -Ofast -ffast-math -funroll-loops -ftree-vectorize \
            -fstrict-aliasing -fno-semantic-interposition \
            -fvect-cost-model=unlimited -fno-trapping-math -fipa-ra \
            -mavx512f -mavx512vl -mavx512bw -mavx512dq -fipa-modref -flto \
            -fassociative-math -fopenmp -mavx2 -mbmi2 -madx \
            -o Cyclone_avx512 \
            Cyclone.cpp SECP256K1.cpp Int.cpp IntGroup.cpp IntMod.cpp Point.cpp \
            ripemd160_avx2.cpp p2pkh_decoder.cpp sha256_avx2.cpp \
            ripemd160_avx512.cpp sha256_avx512.cpp

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cyclone-binaries
        path: |
          Cyclone/Cyclone_avx2/*
          Cyclone/Cyclone_avx512/*
